# Generated by Django 2.2.6 on 2019-11-25 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date',
            new_name='acceptance_date',
        ),
    ]
