# Generated by Django 2.2.6 on 2019-11-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='process',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
