# Generated by Django 2.2.6 on 2019-11-28 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_topic_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='rate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='topics.rate'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='review_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
