# Generated by Django 2.2.6 on 2019-11-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_auto_20191128_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='review_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
